import { drizzle } from 'drizzle-orm/mysql2';
import { pmamDrill } from './drizzle/schema.ts';

const db = drizzle({
  connection: {
    uri: process.env.DATABASE_URL,
  },
});

const drills = [
  // CAPÍTULO II - INSTRUÇÃO INDIVIDUAL SEM ARMA
  {
    title: "Posição de Sentido",
    subtitle: "Posição Fundamental",
    category: "Individual sem Arma",
    difficulty: "basico",
    duration: 10,
    description: "Posição de sentido é a posição fundamental de toda instrução de ordem unida. O militar fica em pé, com os pés juntos e ligeiramente afastados, formando um ângulo de aproximadamente 45 graus.",
    content: "A posição de sentido caracteriza-se por: pés unidos e ligeiramente afastados (ângulo de 45°); corpo ereto; braços ao longo do corpo; mãos abertas com os dedos unidos; olhar para frente; queixo ligeiramente retraído; ombros ligeiramente para trás.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Nenhum",
    learningOutcomes: "Dominar a posição fundamental de sentido",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Posição de Descanso",
    subtitle: "Posição de Repouso",
    category: "Individual sem Arma",
    difficulty: "basico",
    duration: 10,
    description: "Posição de descanso é utilizada para repouso durante a instrução, mantendo a disciplina e a postura militar.",
    content: "Na posição de descanso: pé esquerdo avança aproximadamente 30 cm; peso do corpo distribui-se entre os dois pés; braços ao longo do corpo; olhar para frente; corpo mantém postura ereta.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Posição de Sentido",
    learningOutcomes: "Executar a posição de descanso com disciplina",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Passo Ordinário",
    subtitle: "Movimento de Marcha Básico",
    category: "Individual sem Arma",
    difficulty: "basico",
    duration: 15,
    description: "O passo ordinário é o movimento fundamental de marcha, executado com cadência e ritmo regulares.",
    content: "Características do passo ordinário: comprimento de aproximadamente 75 cm; cadência de 120 passos por minuto; movimento coordenado de braços e pernas; postura ereta durante toda a execução.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Posição de Sentido",
    learningOutcomes: "Executar o passo ordinário com cadência correta",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Passo Acelerado",
    subtitle: "Marcha em Ritmo Acelerado",
    category: "Individual sem Arma",
    difficulty: "intermediario",
    duration: 15,
    description: "Marcha executada com cadência aumentada, mantendo a disciplina e a formação.",
    content: "O passo acelerado caracteriza-se por: cadência de 180 passos por minuto; comprimento de passo aumentado; movimento mais dinâmico; manutenção da postura militar.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Passo Ordinário",
    learningOutcomes: "Executar marcha acelerada com precisão",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Volta à Direita",
    subtitle: "Rotação para a Direita",
    category: "Individual sem Arma",
    difficulty: "intermediario",
    duration: 10,
    description: "Movimento de rotação do corpo para a direita, executado com precisão e sincronismo.",
    content: "Execução da volta à direita: pivô no calcanhar direito; rotação de 90 graus; movimento sincronizado; manutenção da postura ereta; conclusão em posição de sentido.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Posição de Sentido",
    learningOutcomes: "Executar voltas com precisão geométrica",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Volta à Esquerda",
    subtitle: "Rotação para a Esquerda",
    category: "Individual sem Arma",
    difficulty: "intermediario",
    duration: 10,
    description: "Movimento de rotação do corpo para a esquerda, executado com precisão e sincronismo.",
    content: "Execução da volta à esquerda: pivô no calcanhar esquerdo; rotação de 90 graus; movimento sincronizado; manutenção da postura ereta; conclusão em posição de sentido.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Posição de Sentido",
    learningOutcomes: "Executar voltas com precisão geométrica",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Meia Volta",
    subtitle: "Rotação de 180 Graus",
    category: "Individual sem Arma",
    difficulty: "intermediario",
    duration: 10,
    description: "Rotação completa de 180 graus, invertendo a direção do militar.",
    content: "Execução da meia volta: pivô no calcanhar direito; rotação de 180 graus; movimento único e sincronizado; manutenção da postura; conclusão em posição de sentido voltado para trás.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Posição de Sentido",
    learningOutcomes: "Executar meia volta com precisão",
    authorId: 1,
    isActive: true,
  },

  // CAPÍTULO III - INSTRUÇÃO INDIVIDUAL COM ARMA
  {
    title: "Posição de Sentido com Fuzil",
    subtitle: "Posição Fundamental com Arma",
    category: "Individual com Arma",
    difficulty: "intermediario",
    duration: 15,
    description: "Posição de sentido adaptada para execução com fuzil, mantendo o controle da arma.",
    content: "Na posição de sentido com fuzil: pés na mesma posição; fuzil apoiado no ombro direito; cano para cima; mão direita na coronha; mão esquerda na guarda; olhar para frente.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Posição de Sentido, Familiarização com Fuzil",
    learningOutcomes: "Dominar posição de sentido com arma",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Apresentar Arma",
    subtitle: "Movimento de Apresentação do Fuzil",
    category: "Individual com Arma",
    difficulty: "intermediario",
    duration: 15,
    description: "Movimento de apresentação da arma, executado com precisão e respeito.",
    content: "Execução do apresentar arma: movimento único e sincronizado; fuzil trazido à frente do corpo; cano para cima; braços em posição específica; conclusão em posição de sentido com arma apresentada.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Posição de Sentido com Fuzil",
    learningOutcomes: "Executar apresentação de arma com precisão",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Ombro Arma",
    subtitle: "Movimento de Colocar Arma no Ombro",
    category: "Individual com Arma",
    difficulty: "intermediario",
    duration: 15,
    description: "Movimento de colocar o fuzil ao ombro, passando pela posição de apresentar arma.",
    content: "Execução do ombro arma: movimento sincronizado em dois tempos; fuzil trazido ao ombro direito; cano para cima; mão direita na coronha; mão esquerda na guarda; conclusão em posição de sentido com arma ao ombro.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Apresentar Arma",
    learningOutcomes: "Executar ombro arma com precisão",
    authorId: 1,
    isActive: true,
  },

  // CAPÍTULO IV - INSTRUÇÃO COLETIVA
  {
    title: "Formação em Linha",
    subtitle: "Formação Básica Coletiva",
    category: "Coletiva",
    difficulty: "intermediario",
    duration: 20,
    description: "Formação em linha é a disposição de militares em uma única fileira, lado a lado.",
    content: "Características da formação em linha: militares dispostos lado a lado; distância de 0,5 m entre ombros; alinhamento visual; sincronismo de movimentos; manutenção da formação durante deslocamentos.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Posição de Sentido, Passo Ordinário",
    learningOutcomes: "Formar e manter linha com precisão",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Formação em Coluna",
    subtitle: "Formação em Profundidade",
    category: "Coletiva",
    difficulty: "intermediario",
    duration: 20,
    description: "Formação em coluna é a disposição de militares em fila, um atrás do outro.",
    content: "Características da formação em coluna: militares dispostos em fila; distância de 1 m entre fileiras; alinhamento frontal; sincronismo de movimentos; manutenção da formação durante deslocamentos.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Posição de Sentido, Passo Ordinário",
    learningOutcomes: "Formar e manter coluna com precisão",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Formação em Quadrado",
    subtitle: "Formação Defensiva",
    category: "Coletiva",
    difficulty: "avancado",
    duration: 30,
    description: "Formação em quadrado é a disposição de militares formando um quadrilátero, utilizada para defesa.",
    content: "Características da formação em quadrado: militares dispostos formando quadrado; faces voltadas para exterior; sincronismo total; manutenção da formação sob pressão; coordenação de movimentos.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Formação em Linha, Formação em Coluna",
    learningOutcomes: "Formar e manter quadrado com precisão",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Deslocamento de Frente",
    subtitle: "Marcha Coletiva para Frente",
    category: "Coletiva",
    difficulty: "intermediario",
    duration: 20,
    description: "Deslocamento de toda a formação para frente, mantendo alinhamento e sincronismo.",
    content: "Execução do deslocamento de frente: comando verbal ou gestual; movimento sincronizado de toda a tropa; manutenção da formação; cadência uniforme; conclusão em nova posição.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Formação em Linha, Passo Ordinário",
    learningOutcomes: "Deslocar formação com precisão",
    authorId: 1,
    isActive: true,
  },

  // CAPÍTULO V - COMANDO POR GESTOS
  {
    title: "Gesto de Atenção",
    subtitle: "Comando Gestual de Alerta",
    category: "Comando por Gestos",
    difficulty: "basico",
    duration: 5,
    description: "Gesto utilizado para chamar atenção da tropa antes de um comando.",
    content: "Execução do gesto de atenção: braço direito levantado; mão aberta; movimento único e visível; todos os militares devem responder com atenção redobrada.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Nenhum",
    learningOutcomes: "Reconhecer e responder ao gesto de atenção",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Gesto de Marcha",
    subtitle: "Comando Gestual para Iniciar Marcha",
    category: "Comando por Gestos",
    difficulty: "basico",
    duration: 5,
    description: "Gesto utilizado para ordenar o início da marcha.",
    content: "Execução do gesto de marcha: braço direito levantado e abaixado; movimento rápido e definido; todos iniciam marcha sincronizadamente.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Gesto de Atenção",
    learningOutcomes: "Reconhecer e responder ao gesto de marcha",
    authorId: 1,
    isActive: true,
  },
  {
    title: "Gesto de Parada",
    subtitle: "Comando Gestual para Parar",
    category: "Comando por Gestos",
    difficulty: "basico",
    duration: 5,
    description: "Gesto utilizado para ordenar a parada da marcha.",
    content: "Execução do gesto de parada: braço levantado com mão aberta; movimento único; todos param sincronizadamente; conclusão em posição de sentido.",
    instructor: "Manual EB70-MC-10.308",
    prerequisites: "Gesto de Marcha",
    learningOutcomes: "Reconhecer e responder ao gesto de parada",
    authorId: 1,
    isActive: true,
  },
];

async function seedDrills() {
  try {
    console.log('Iniciando seed de Ordens Unidas...');
    
    for (const drill of drills) {
      await db.insert(pmamDrill).values(drill);
      console.log(`✓ Carregada: ${drill.title}`);
    }
    
    console.log(`\n✓ ${drills.length} Ordens Unidas carregadas com sucesso!`);
    process.exit(0);
  } catch (error) {
    console.error('Erro ao carregar Ordens Unidas:', error);
    process.exit(1);
  }
}

seedDrills();
